spring:
  application:
    name: lab-module2-project1

  #??? .env
  datasource:
    url: jdbc:postgresql://localhost:5432/kaspi-lab
    username: khatep
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  #create validate
    show-sql: true
    open-in-view: false

feign:
  clients:
    kaspi-lab:
      delivery-service: localhost:8081

app:
  security:
    username: admin
    password: pass123

server:
  port: 8080
  servlet:
    context-path: /

