spring:
  application:
    name: lab-module2-project1

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kaspi-lab
    username: khatep
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

clients:
  kaspi-lab:
    delivery-service: http://localhost:8081

app:
  security:
    username: admin
    password: pass123

server:
  port: 8080
